### ISSUE TITLE
I can't tell if the 'createhook' action is working or not

### ISSUE THREAD

**Issue by chaismeyer** [grokify/ringcentral-permahooks#1]
Thank you for this!

I've installed go server locally, setup ngork (it's running successfully), I've modified my credentials and I'm trying to run the go.server file. 

I say "Trying" because even though I'm following your instructions nothing is happening after I 'createhook.' http://example.24hrtees.net/olL8

One thing I'm confused about, how do I know if the 'createhook' action is working? Will there be an actual file output somewhere (like to the directory where my ngrok URL is pointing)?

Finally, I noticed that your "MY_URL" example ended with the directory of "/webhook/" I currently have mine (in the .ent file) going to the direct ngrok URL (which ultimately is going to my localhost on my computer) with no additional directories at the end of the URL. Is this accurate?

**Comment by grokify** [comment]
When you run this can call '/createhook' it will create log entries like the following showing that it started creating the webhook and successfully received a `subscriptionId`:

```bash
$ go run server.go 
INFO[0023] Creating Hook...                             
INFO[0024] {"eventFilters":["/restapi/v1.0/account/~/extension/~/message-store/instant?type=SMS","/restapi/v1.0/subscription/~?threshold=86400\u0026interval=3600"],"deliveryMode":{"transportType":"WebHook","address":"https://12345678.ngrok.io/webhook"},"expiresIn":604800} 
INFO[0025] Handling webhook...                          
INFO[0025] Validation-Token: 11112222-3333-4444-5555-666677778888
INFO[0025] Created/renewed Webhook with Id: 11112222-3333-4444-5555-666677778888
```

In the initial version, the URL should be `/webhook` without a trailing `/` but I've updated the code to allow a trailing slash and added the above example to the docs.

**Comment by chaismeyer** [comment]
You're doing a great job helping, thank you! I'm still missing something though.

I made a short video to explain where I'm stuck, hopefully, this will help you understand what I know (very little) and where I might be doing something wrong. https://youtu.be/uyZCU8wwJH8

Any help you can provide is very much appreciated (if you were closer, I'd buy you a beer)!

**Comment by grokify** [comment]
Hi @chaismeyer,

Thanks for sending the video. It is very helpful and it looks like you have just about everything working. From looking at it, the `curl` command won't execute because server.go is running as a foreground process which will block any other command from happening, including curl. To get around this for testing purposes, you can:

* run the curl command from a different terminal window/tab
* run `server.go` as a background process

Running as a background process will return your terminal to a command prompt which will process subsequent commands. You can do this by adding a `&` to the end like `$ go run server.go &`. This will return a process ID (aka `PID`) and return you to the prompt. When running in the foreground, you can stop the process with `Control+C`. When running in the background, you need to stop the process by killing the `PID` which you can do with `$ kill $PID` , e.g. `$ kill 12345`

Either of these approaches should solve this issue for testing purposes, which these instructions are for.

To run this in production you will want to build a binary and run this as a background process.

Here's more information on foreground and background processes:

https://unix.stackexchange.com/questions/175741/what-is-background-and-foreground-processes-in-jobs

**Comment by chaismeyer** [comment]
This is great information as I had no idea I had to run the curl command in a different terminal window/tab, so thank you for that!

When I do jump into a new tab (after the server's running) and run the curl command, here's the response I get:
<img width="871" alt="terminal-response" src="https://user-images.githubusercontent.com/32783035/34860368-82a02212-f722-11e7-9320-7711f9473b81.png">

To me, it's acting like it's trying to find a directory called "/createhook" at the location where my ngrok link is pointing, which is my local Mac OSX webserver (on port 80). Here are the folders on my webserver by default: 
<img width="788" alt="webserver folders" src="https://user-images.githubusercontent.com/32783035/34860380-a154f412-f722-11e7-9860-3af8a20a267c.png">


When I go into my "Documents" folder, this is where I can find my "test.php" file...
<img width="862" alt="webserver php file" src="https://user-images.githubusercontent.com/32783035/34860335-495dcad6-f722-11e7-815a-4ae4d0b1ce83.png">


...Which is ultimately the file that shows up when I go to my ngrok URL: 
<img width="662" alt="webserver file" src="https://user-images.githubusercontent.com/32783035/34860266-f58f7f6c-f721-11e7-8a88-f30a63600e6c.png">


So I guess my question is, should I have my go server installed inside my webserver directory or do I somehow need to setup my ngork URL to point to my specific folder directory outside of my localhost webserver (not even sure if that's possible)? OR...maybe I'm not even asking the right questions...

Again, you're doing a great job explaining all of this, I'm sorry for the hassle of you not knowing all of the variables on my end.

**Comment by grokify** [comment]
By default, `ringcentral-permahooks` runs on port `8080`. You have another local webserver running port `80`.

From the following `ngrok` lines, it is configured to forward to your other local webserver port on `80` not, the permahooks app on `8080:

```
Forwarding http://12345678.ngrok.io -> localhost:80
Forwarding https://12345678.ngrok.io -> localhost:80
```

To connect `ngrok` to port `8080` start `ngrok` with the following:

`$ ngrok http 8080`

When ngrok runs, you will now see something like the following:

```
Forwarding http://12345678.ngrok.io -> localhost:8080
Forwarding https://12345678.ngrok.io -> localhost:8080
```

You can change the port `ringcentral-permahooks` runs on but setting the `PORT` environment variable. `PORT` is used because this is also used by Heroku. You can set this in the `.env` file.

BTW, using GitHub issues is fine for this. I think this format may be better to resolve this particular issue than Stack Overflow which is more for programming questions than installation/configuration troubleshooting.

**Comment by chaismeyer** [comment]
Perfect, after changing the port it made ALL the difference when it comes to connecting!

Now I'm having an error message that pops up in the console log: "error: CMN-101"
<img width="1145" alt="console-error" src="https://user-images.githubusercontent.com/32783035/34896302-eca42fa0-f7ae-11e7-8398-0c68ffc60bcb.png">

Looks like this is the error:
<img width="663" alt="error-codes-doc" src="https://user-images.githubusercontent.com/32783035/34896390-46df77ea-f7af-11e7-85ae-f84ce3469382.png">


Here's a video that shows this (specifically where it errors out): http://example.24hrtees.net/opRb

We're so close I can taste it, I'm just not sure what entries would be considered invalid.


And yes, I'm going to make a complete video tutorial (for newbies like me) explaining how to setup this test for themselves, so that others can avoid the simple mistakes I've made so far. :)

**Comment by grokify** [comment]
Good eyes. The `sample.env` file was out of date and I've updated it out.

The two environment variables are:

* `PERMAHOOKS_INBOUND_WEBHOOK_URL` - into this service, e.g. ngrok
* `PERMAHOOKS_OUTBOUND_WEBHOOK_URL` - out of the service, e.g. to Zapier

**Comment by chaismeyer** [comment]
Great, I have the sample.env updated with the new code. After the update and save I ran the curl script and below is what I still get.

I still can't figure out this error, any thoughts on this?
<img width="1395" alt="terminal-error" src="https://user-images.githubusercontent.com/32783035/34910319-deca6f9c-f877-11e7-8911-6fb0ca97316a.png">

**Comment by grokify** [comment]
The error indicates that the address isn't being read.

In the log line you will see `"deliveryMode":{"transportType":"WebHook"}` which doesn't have an address. It should have an `address` property and look something like `"deliveryMode":{"transportType":"WebHook","address":"https://12345678.ngrok.io/webhook"}`.

You wrote that you updated `sample.env`. You should update the `.env`. In the docs you can see this as the following but I'll add additional text to the `README.md`.

```bash
$ cp sample.env .env
$ vi .env
```

For this app, you can alternately specify another `.env` file by using the `ENV_PATH` environment variable.

Try setting all the correct variables in the `.env` file.

**Comment by chaismeyer** [comment]
Sorry about that, I typed my previous reply wrong...

I updated the sample.env and the .env to match, then I filled in with the correct credentials and tested. Still getting the same error.

Here is a screenshot of my .env file:
<img width="504" alt="vi env - version 2" src="https://user-images.githubusercontent.com/32783035/34920777-ed5ab398-f93d-11e7-9a21-9cd13d32ac38.png">

Here is a gif of the error I'm getting after the .env is updated with the URL (with the same error despite the URL being in place):
![curl-gif](https://user-images.githubusercontent.com/32783035/34920789-58a6fbf2-f93e-11e7-99b3-faae3d9ff4bc.gif)

Thanks again for the assistance with this!

**Comment by grokify** [comment]
Can you update your code and try again.

Use the the following to update the package:

```
$ go get -u github.com/grokify/ringcentral-permahooks
```

This is the entry for the `-u` flag from the help: `go get -h`:

> The -u flag instructs get to use the network to update the named packages and their dependencies. By default, get uses the network to check out missing packages but does not use it to look for updates to existing packages.

**Comment by chaismeyer** [comment]
Ok, I updated the code and had an error pop up that said: 
> error: Your local changes to the following files would be overwritten by merge:
.env
sample.env
Please, commit your changes or stash them before you can merge.

So I googled how to delete my local changes and the winning advice was this:
`git reset --hard`
And then...
`$ git clean -dfx`

So I ran those above commands and then updated the package (with no subsequent errors) using:
`$ go get -u github.com/grokify/ringcentral-permahooks`

I copied the sample.env into an ".env" file using this code:
`$ cp sample.env .env`

I edited the template '.env' file (filling in all my information again via "i" for 'insert'), using:
`$ vi .env`
saving this file by escaping out of the 'insert' function and saving using:
`:wq`

Then I ran the file using (on my already running server and verifying my ngrok link was operational still - using the 8080 port):
`$ curl -XGET 'https://0bf24ac8.ngrok.io/createhook'`

Unfortunately, I get the same error message! :(
`INFO[31182] API Response Err: Status: 400 Bad Request, Body: {"errorCode":"InvalidParameter","message":"Parameter [deliveryMode.address] value is invalid","errors":[{"errorCode":"CMN-101","message":"Parameter [deliveryMode.address] value is invalid","parameterName":"deliveryMode.address"}],"parameterName":"deliveryMode.address"} `

Did I miss something? 
Do I need to shut the server down before updating the files and then start it again after file update?

**Comment by grokify** [comment]
Can you show the log line with `"deliveryMode":{"transportType":"WebHook"` in it? Previously, the webhook address wasn't being read, and this version should catch that before making the API call.

**Comment by chaismeyer** [comment]
Here's the exact (full error) I'm getting this time:
<img width="773" alt="console-error_v 2" src="https://user-images.githubusercontent.com/32783035/34922704-22e1d0bc-f959-11e7-8543-e232ef872074.png">

Here's the error I got previous, before the recent code update:
<img width="1145" alt="console-error" src="https://user-images.githubusercontent.com/32783035/34922711-35923116-f959-11e7-9645-86b0c946b13e.png">

**Comment by grokify** [comment]
What you're showing shouldn't be happening with the latest code.

Can you show everything up to and including `Creating Hook...`. You should see something like the following:

```bash
$ go run server.go 
INFO[0000] Listening on port 8080                       
INFO[0014] [::1]:56537 GET /createhook                  
INFO[0014] Creating Hook...
```

**Comment by chaismeyer** [comment]
**Ok, here's what I see after running the git log:**
<img width="727" alt="git-log" src="https://user-images.githubusercontent.com/32783035/34924290-2e361c48-f968-11e7-8a9e-86d61a306b73.png">

**Here's terminal, after I ran everything again just a few minutes ago:**
<img width="728" alt="go server-after-update" src="https://user-images.githubusercontent.com/32783035/34924457-0c1b5ce4-f969-11e7-8844-4845c88aacea.png">

**Comment by grokify** [comment]
Okay, that is progress. Your request now has `deliveryMode.address` populated.

The error now says you need to have the `SubscriptionWebhook` permission:

`[SubscriptionWebhook] application permission is required for [WebHook] transport`

In the Developer Portal, make sure you have this permission enabled. It is called `Webhook Subscriptions` as shown below. I've updated the `README.md` to indicate the necessary permissions which should also include `Read Messages`:

<img width="332" alt="ringcentral-permahooks_app_configuration" src="https://user-images.githubusercontent.com/209872/34939086-718fe26c-f99f-11e7-821d-961d9b409c49.png">

**Comment by chaismeyer** [comment]
GREAT!
I'v finally run the process of creating a webhook successfully, but I don't think I setup my ringcentral app appropriately, according to your updated read.me. 

I'm going to recreate the app, but before I do, what should I choose for this section (since I'm unable to change it after the fact)?
<img width="828" alt="api-type-of-app" src="https://user-images.githubusercontent.com/32783035/34958388-5e12f71c-f9f7-11e7-89f1-e20703eeb95a.png"> 

Thanks again @grokify, you've been doing a fabulous job working with me and I'm incredibly grateful for your patience!

**Comment by grokify** [comment]
I'll provide some info on the Zapier test here. I'll respond to the "App Type & Platform" question in the next post.

> I tried running the zapier test, but it doesn't find anything so I think the problem are the settings on the ringcentral app.

Try to send a SMS to the phone number. When you do, you should see some log entries like the following.

```
INFO[0015] 127.0.0.1:56080 POST /webhook                
INFO[0015] Handling webhook...
```

If you set the log level to debug using `log.SetLevel(log.DebugLevel)`, you should see each incoming message in the logs:

```
INFO[0007] 127.0.0.1:56165 POST /webhook                
INFO[0007] Handling webhook...                          
DEBU[0007] {"uuid":"3213530895399200455","event":"/restapi/v1.0/account/130709004/extension/130836004/message-store/instant?type=SMS","timestamp":"2018-01-15T21:27:12.702Z","subscriptionId":"7b17e197-b75f-4726-bec2-b15cdf4f78d1","ownerId":"130836004","body":{"id":"3922393004","to":[{"phoneNumber":"+15856234090","name":"Tiger RingForce","location":"Rochester, NY"}],"from":{"phoneNumber":"+17752204114","location":"Sparks / Elko / Fallon / Fernley / Golconda / Incline Village / Pahrump / Spring Creek / Sun Valley / Washoe Valley / Winnemucca / Zephyr Cove, NV"},"type":"SMS","creationTime":"2018-01-15T21:27:12.654Z","lastModifiedTime":"2018-01-15T21:27:12.654Z","readStatus":"Unread","priority":"Normal","attachments":[{"id":"3922393004","type":"Text","contentType":"text/plain"}],"direction":"Inbound","availability":"Alive","subject":"Hello world!","messageStatus":"Received"}} 
```

After the message is posted to Zapier, if there's an error, you should see a log message starting with the following:

`Downstream webhook error:`

I'll think about updating this to:

* Making log level configurable from `.env` file
* Add success message for calling downstream service

**Comment by grokify** [comment]
Regarding the following issue:

> I'm going to recreate the app, but before I do, what should I choose for this section (since I'm unable to change it after the fact)?
> <img width="828" alt="api-type-of-app" src="https://user-images.githubusercontent.com/32783035/34958388-5e12f71c-f9f7-11e7-89f1-e20703eeb95a.png"> 
> I'm planning on having this run on a third party server for the time-being.

Right now, this app will only run as a private app meaning, running with your own RingCentral account. Enhancements are needed to run as a public app where a single app deployment can work with multiple RingCentral accounts.

Running on a 3rd party service is fine and does not affect the above choice.

**Comment by chaismeyer** [comment]
It looks like I'm unable to just choose "password flow" (ONLY) as my authorization flow because I'm required to choose a platform type. When I choose a platform type it automatically changes my authorization flows and doesn't allow me to just choose one:
![auth-flow-platform-type-selection](https://user-images.githubusercontent.com/32783035/34965867-0c0b8fda-fa1d-11e7-9faa-32f807b1fcd7.gif)

After I've set everything else up the way I think it needs to be set in the ringcentral app:
<img width="837" alt="rc-app-settings" src="https://user-images.githubusercontent.com/32783035/34966427-1fc32d4a-fa21-11e7-80ea-fc064bd1d84f.png">

Terminal says that everything is working well, but there are no logs being displayed when I send or receive text messages from the phone number.
<img width="859" alt="go-server-success" src="https://user-images.githubusercontent.com/32783035/34966390-e94f2afc-fa20-11e7-9e0b-a28ff8bfa909.png">

**Comment by grokify** [comment]
The following is fine:

* Application Type: `Private`
* Platform Type: `Server-only (No UI)`
* Authorization Flows: `Refresh Access Token`, `Password flow`

**Comment by grokify** [comment]
> Terminal says that everything is working well, but there are no logs being displayed when I send or receive text messages from the phone number (this log was immediately after I sent and received a text from this number/extension).

If you receive a text, you should get an event and see log entries written. The issue may be the app is listening on a different extension than you are calling. Is your `RINGCENTRAL_USERNAME` value the same as the phone number you are texting? If not, does the number you are texting to belong to the extension specified by `RINGCENTRAL_USERNAME`?

**Comment by chaismeyer** [comment]
Thanks for the reply @grokify - I'll test everything again tonight sometime to see what's up. 

Yes, the `RINGCENTRAL_USERNAME` is my primary phone number given to me by RingCentral when I first setup my account (which is assigned to my primary extension). 

I just texted this `RINGCENTRAL_USERNAME` number, and it did not show up in my ringcentral softphone app, so I'm going to try my other (ported) number in the webhook settings, despite the RingCentral developer app telling me I should use the primary username (which is listed in my "User Account Credentials" section of the developer portal).

I'll let you know what I find out.

**Comment by grokify** [comment]
@chaismeyer 

In your screenshot, the left column says "Sandbox Environment" and the right column says "Production Environment". The user credentials including "Username" and "Password" are different for the two environments as are the app credentials including "Client ID" and "Client Secret".

You cannot change them to be the same right now. You pick the app and user credentials for the environment you are using. For example, during testing, you use "Sandbox Environment" app and user credentials. After you graduate your app, you use the "Production Environment" app and user credentials.

See more here:

https://developer.ringcentral.com/library/getting-started.html

**Comment by grokify** [comment]
Closing due to inactivity. Please post again if you still have issues.
